services:

  api:
    container_name: evolution_api
    image: atendai/evolution-api
    restart: always
    ports:
      - 8081:8080
    volumes:
      - ./evolution_instances:/evolution/instances
      - ./evolution_store:/evolution/store
    env_file:
      - .env
    command: ['node', './dist/src/main.js']
    expose:
      - 8081
