services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3001:8080
    volumes:
      - ./open-webui-data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
