services:
  anthropic:
    image: ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
    ports:
      - "5900:5900"
      - "8501:8501"
      - "6080:6080"
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./anthropic:/home/computeruse/.anthropic
    tty: true