version: "3"

services:
 
  BaseDeDatos:
    image: linuxserver/mariadb:10.11.5
    container_name: BaseDeDatosTest
    env_file:
      - mariadb.env
    volumes:
      - ./MariaDB:/config
    ports:
      - 3306:3306
    restart: unless-stopped
